snapshot:
  name_template: "v{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^examples:'
builds:
  - id: tg
    binary: tg
    goos:
    - linux
    - freebsd
    - darwin
    goarch:
    - amd64
    env:
    - CGO_ENABLED=0

archives:
  - id: tg
    format: binary
    builds:
    - tg
