before:
  hooks:
    - go mod download
    - go generate ./...
build:
  skip: true
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
