name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.25"

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0

      - name: build
        run: |
          make

      #- uses: PaloAltoNetworks/cov@3c863a1458c9ae685c4332af25700920818aa0d2 # 3.0.0
      #  with:
      #    main_branch: master
      #    cov_file: unit_coverage.out
      #    cov_threshold: "45"
      #    cov_mode: coverage
