name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.20"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: setup
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: build
        run: |
          make

      - uses: PaloAltoNetworks/cov@3.0.0
        with:
          main_branch: master
          cov_file: unit_coverage.out
          cov_threshold: "45"
          cov_mode: coverage
