name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.18
          - 1.19
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: setup
        run: |
          go version
          go install github.com/securego/gosec/cmd/gosec@latest
          #go get golang.org/x/tools/cmd/cover
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: build
        run: |
          make

      # note: uncertain how gracefully this handles the matrix
      # note: I disabled this because codacy returns a 502
      # - name: coverage
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      #     # a comma-separated list
      #     coverage-reports: "./coverage.xml"
