name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.23"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: >
            --disable-all
            --exclude-use-default=false
            --exclude=package-comments
            --exclude=unused-parameter
            --enable=errcheck
            --enable=goimports
            --enable=ineffassign
            --enable=revive
            --enable=unused
            --enable=staticcheck
            --enable=unconvert
            --enable=misspell
            --enable=prealloc
            --enable=nakedret
            --enable=unparam
            --enable=typecheck

      - name: build
        run: |
          make

      - uses: PaloAltoNetworks/cov@3.0.0
        with:
          main_branch: master
          cov_file: unit_coverage.out
          cov_threshold: "45"
          cov_mode: coverage
